import { run_basic_examples } from "./basics.ts";
import { run_builtin_shape_examples } from "./built_in_shapes.ts";
import { run_composable_function_examples } from "./composable_functions.ts";
import { run_custom_typeclass_examples } from "./custom_typeclass.ts";
import { run_do_context_examples } from "./do_contexts.ts";
import { run_effect_examples } from "./effects.ts";
import { run_instrumented_effect_examples } from "./instrumented_effects.ts";
import { run_keyed_cell_examples } from "./keyed_cells.ts";
import { run_matching_examples } from "./matching.ts";
import { run_monad_examples } from "./monads.ts";
import { run_stm_coordination_examples } from "./stm_coordination.ts";
import { run_task_workflow_examples } from "./task_workflow.ts";
import { run_validated_request_examples } from "./validated_request.ts";
import { run_worker_pool_examples } from "./worker_pool.ts";

await run_basic_examples();
run_do_context_examples();
run_validated_request_examples();
run_composable_function_examples();
await run_builtin_shape_examples();
await run_monad_examples();
await run_task_workflow_examples();
await run_worker_pool_examples();
run_stm_coordination_examples();
await run_effect_examples();
run_instrumented_effect_examples();
run_keyed_cell_examples();
run_matching_examples();
run_custom_typeclass_examples();
